[project]
name = "odoo-addons-oca-credit-control"
version = "19.0.20260316.0"
dependencies = [
    "odoo-addon-account_financial_risk==19.0.*",
    "odoo-addon-sale_financial_risk==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
